#!/bin/bash

docker exec -it php bash -c "sudo -u devuser /bin/bash"

docker run -it php cmd

##START
#docker-compose build && docker-compose up -d
#
##ARTISAN
#docker exec php php /var/www/html/artisan migrate
#
##MIGRATE
#docker exec php php /var/www/html/artisan make:migration create_ticket_points_table
#
#docker exec php php /var/www/html/artisan migrate:refresh
#
#docker exec php php /var/www/html/artisan ui vue --auth